### ISSUE TITLE
[MAJOR BUG] website won't open😂😂

### ISSUE THREAD

**Issue by revintec** [RisingStack/nx-framework#21]
![image](https://user-images.githubusercontent.com/8952734/33939710-2279220e-e047-11e7-8833-204cbd90fd6a.png)
![image](https://user-images.githubusercontent.com/8952734/33939715-272c0366-e047-11e7-84c0-f2e35f2201f8.png)
![image](https://user-images.githubusercontent.com/8952734/33939717-2918b14c-e047-11e7-9caf-412528ba2d6f.png)

**Comment by lastboy** [comment]
+1
Is there a way to get to the docs other than nx-framework.com ?

**Comment by solkimicreb** [comment]
Ouch 🙁 The site is back up, I migrated it to `now`. The project is still on hold because of my lack of time though. I will get back to it later.

**Comment by lastboy** [comment]
Oh... great news!!
Thank you @solkimicreb

**Comment by revintec** [comment]
@solkimicreb thanks, has been a long time though :)
