### ISSUE TITLE
Plans for wider browser support

### ISSUE THREAD

**Issue by solkimicreb** [RisingStack/nx-framework#3]
As you may know some browsers are not yet supported, because of the use of unpolyfillable ES6 Proxies in [this helper library](https://github.com/RisingStack/nx-observe). This is a proposal to add a fallback for those browsers.

The [NX core](https://github.com/RisingStack/nx-framework/tree/master/core) sets up hooks (middlewares) on DOM element attachments. Other then this it does a few other things, like transforming the state object into an observable object (this is where Proxies are used).

I plan to move everything other then the hook definitions out of the core into [separate middlewares](https://github.com/RisingStack/nx-framework/tree/master/middlewares). I would move the code using the Proxy into a middleware called `observe` and create an alternative `legacy-observe` middleware that uses getters/setter instead of Proxies for data binding.

This way, the only thing you would have to do to achieve wider browser support is replacing `comp.useOnContent(observe)` with `comp.useOnContent(legacyObserve)` in the [app component](https://github.com/RisingStack/nx-framework/blob/master/components/app.js) you use. The limitation of using `legacyObserve` would be not being able to bind on getters/setters and expando properties (this is a big one.) These limitations are present with all current data binding techniques that I know of others than the Proxy method.

What is your opinion, is it understandable?

**Comment by rockcoder23** [comment]
It sounds good~

**Comment by solkimicreb** [comment]
All the preparations are ready. The core is now totally pure, it includes only DOM hooks and no observer logic. The `legacyObserve` middleware is scheduled after the beta release (which will happen on the first week of January).

**Comment by solkimicreb** [comment]
I am closing this issue for now. I still plan to work on this, but it won't happen soon.
