### ISSUE TITLE
No test?

### ISSUE THREAD

**Issue by zhuzhuaicoding** [RisingStack/nx-framework#6]
Would you support some tests for me ? I think It is easy to understand your intention.

**Comment by solkimicreb** [comment]
Unfortunately there are no tests yet. I use the live editable examples and the home page itself as a rough test for now.
The plan is to have 100% test coverage before the beta. It is not the most fun part but some help would be really appreciated if you are good with testing :smile:

P.S: I am not sure if I understood you question correctly
