### ISSUE TITLE
Roadmap until beta

### ISSUE THREAD

**Issue by solkimicreb** [RisingStack/nx-framework#7]
These are the changes I would like to happen before NX beta is released. In my opinion the beta should be as stable as possible to let us focus on bug fixes and documentation improvements. With a good pace the below changes should take around 2-3 months. What is your opinion? Would you like to see a stricter roadmap with rough deadlines?

**Framework changes:**
- form validation middleware **POSTPONED**
- transition/animation middleware **DONE**
- change Custom Elements polyfill to a subset of the official v1 polyfill **POSTPONED (native implementation of type extension is buggy)**
- Shadow DOM support (requires changes in core and the render middleware) **DONE**
- Scoped styles support **DONE**
- optimize the nx-compile and nx-observe helper libraries for speed **DONE**
- determine a list of officially supported browsers with exact versions
- get 100% test coverage with all supported browsers
- setup a linter

**Small fixes and refactors:**
- refactor core and all middlewares one by one: main goal is speed and readabilty **DONE**
- fix all reported bugs (naturally)

**Docs and utilities:**
- NX-CLI for project seed generation
- complex example apps and walk throughs written in NX **IN PROGRESS**
- home page cleanup and public release for contributors (the home page is an NX app)
- documentation for contributors
- separate, short API documentation instead of 'cheat sheets'

**What comes after the beta:**
- unofficial API freeze, breaking changes will happen only if unavoidable
- release a distributed version of NX, where every middleware is in its own repo (something similar to what Express is doing)

**Comment by NetOpWibby** [comment]
I like it! Looking forward to using this after the beta! It would be neat if there was a flag for when a site using NX is accessed by an unsupported browser so I could easily set up a message for those users.

**Comment by solkimicreb** [comment]
Great idea, I will include it in the next release. Sorry for the (very) late response.

EDIT: Flag is available form alpha 6 and up. You can access it as `nx.supported`.
